/**部门树形视图类*/
Ext.define("core.category.view.CategoryTree",{
	extend:"Ext.tree.Panel",
	alias:"widget.categorytree",
	rootVisible:false,   //不展示根节点
	displayField:"text",
	animate:false,   //去掉一些动画效果
	store:"core.category.store.CategoryStore",
	tools:[{
		type:"refresh",
		qtip:"刷新",
		handler:function(event,toolEl,header){
		}
	}],
	rbar:[{
		xtype:"button",
		tooltip:"添加根类别",
		iconCls:"tree_model_add",
		ref:"treeIns"
	},{
		xtype:"button",
		tooltip:"添加子类别",
		iconCls:"tree_func_add",
		disabled:true,
		ref:"treechildIns"
	},{
		xtype:"button",
		tooltip:"删除类别",
		iconCls:"tree_delete",
		disabled:true,
		ref:"treeDel"
	}]
});